# Database connection
spring.datasource.url=

# MySQL driver class
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# username and password
spring.datasource.username=
spring.datasource.password=

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

external.api.url=http://api.carsxe.com
external.api.key=
external.api.key=

spring.sendgrid.api-key=
spring.sendgrid.api-key=

spring.thymeleaf.prefix=classpath:/public/pages/