## Database connection
spring.datasource.url=jdbc:mysql://danov-autoshow.mysql.database.azure.com:3306/autoshow

# MySQL driver class
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# username and password
spring.datasource.username=denko
spring.datasource.password=er7r-anqu

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

external.api.url=http://api.carsxe.com
external.api.key=0we97uq08_lqgnlr9s7_dad5mdh29

spring.sendgrid.api-key=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

spring.thymeleaf.prefix=classpath:/public/pages/

### Database connection
#spring.datasource.url=jdbc:mysql://localhost:3306/autoshow
#
## MySQL driver class
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## username and password
#spring.datasource.username=root
#spring.datasource.password=weather-app23
#
## Hibernate settings
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
#external.api.url=http://api.carsxe.com
#external.api.key=0we97uq08_lqgnlr9s7_dad5mdh29
#
#spring.sendgrid.api-key=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
#
#spring.thymeleaf.prefix=classpath:/public/pages/
