apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
spec:
  replicas: 1  # Number of replicas (pods) to run
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: danovautoshow.azurecr.io/spring-app:latest  # Your Docker image from ACR
        ports:
        - containerPort: 8080  # Port that your Spring Boot application listens on
